### ISSUE TITLE
Port exposed for communications...

### ISSUE THREAD

**Issue by nvrnight** [SteveSandersonMS/BlazorElectronExperiment.Sample#2]
It's a TODO in the code to remove this, figured I'd create an issue for it. If you have any guidance on a library/approach to use or something to replace the code that requires opening the web socket port I can see if I can put some work towards it and send a pull request if I'm successful.

**Comment by SteveSandersonMS** [comment]
Thanks for your interest. I was going to have a go at using stdin/stdout as the comms channel. For the framing/multiplexing, options include:

* Using something like [the infrastructure from NodeServices](https://github.com/aspnet/JavaScriptServices/blob/master/src/Microsoft.AspNetCore.NodeServices.Sockets/PhysicalConnections/StreamConnection.cs) that frames/multiplexes simultaneous messages over a single stream
* Or perhaps in this case it would be sufficient to do something simpler manually, and just require that there's only ever one message in transit at a given instant. Send it with a length prefix, and have the other side send back an ACK when it's got it.

To change the transport, it would be necessary to either fork or replace Electron.NET, because Electron.NET doesn't have any APIs for replacing its built-in transport.
